parameters:
    vmImages: 
      Linux: ubuntu-latest
      MacOS: macos-latest
      Windows: windows-latest
    nodejs:
      - '12'      # latest
      - '10.11.0' # vscode >= 1.36.0
      - '10.2.0'  # vscode >= 1.31.0 < 1.36.0
      - '8.9.3'   # vscode >= 1.26.0 < 1.31.0

jobs:
  - job:
    
    strategy:
      maxParallel: 3
      matrix:
        ${{ each image in parameters.vmImages }}:
          ${{ each version in parameters.nodejs }}:
            '${{ image.key }} NodeJS v${{ version }}':
              imageName: ${{ image.value }}
              version: ${{ version }}
              ${{ if not(contains(version, '.')) }}:
                checkLatest: true
                continueOnError: true # allow failure
       
    pool:
      vmImage: $(imageName)

    steps:
      - task: NodeTool@0
        inputs:
          versionSpec: $(version)
      - script: |
          echo 'node --version' && node --version
          echo 'npm --version' && npm --version
      - template: ../steps/checkout.yml
      - script: npm install
      - template: ../steps/script.yml